### ISSUE TITLE
`can't cd to /home/app/notebook`

### ISSUE THREAD

**Issue by iaindillingham** [ebmdatalab/price-concessions-accuracy-notebook#5]
@richiecroker reports[^1] the following error when he runs `run.exe`:

```
/bin/sh: 1: cd: can't cd to /home/app/notebook
```

I'm unable to build an image from the Dockerfile, but I'm rusty: [`docker build`](https://docs.docker.com/reference/cli/docker/image/build/) doesn't Just Work.

[^1]: https://bennettoxford.slack.com/archives/C051A4P27GE/p1709042398075119

**Comment by inglesp** [comment]
Appears to have fixed itself
